package frontend;

import backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FrmBus extends javax.swing.JFrame {

    public FrmBus() {
        initComponents();
        tampilkanData();
        kosongkanForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        txtIdBus = new javax.swing.JTextField();
        txtNamaBus = new javax.swing.JTextField();
        txtJamBerangkat = new javax.swing.JTextField();
        txtHargaTiket = new javax.swing.JTextField();
        txtTerminalAsal = new javax.swing.JTextField();
        txtTerminalTujuan = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnPenumpang = new javax.swing.JButton();
        btnTiket = new javax.swing.JButton();
        btnReservasi = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnKereta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBus.setBackground(new java.awt.Color(5, 157, 192));
        tblBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBus);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 424, 646, 115));

        jLabel1.setText("ID Bus");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 87, -1, -1));

        jLabel2.setText("Nama Bus");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 133, -1, -1));

        jLabel4.setText("Jam Berangkat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 169, -1, -1));

        jLabel5.setText("Harga Tiket");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 210, -1, -1));

        jLabel6.setText("Terminal Asal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 251, -1, -1));

        jLabel7.setText("Terminal Tujuan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 291, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 349, -1, -1));

        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 383, -1, -1));

        txtIdBus.setEnabled(false);
        getContentPane().add(txtIdBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 84, 92, -1));
        getContentPane().add(txtNamaBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 125, 284, -1));
        getContentPane().add(txtJamBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 166, 284, -1));
        getContentPane().add(txtHargaTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 207, 284, -1));
        getContentPane().add(txtTerminalAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 248, 284, -1));
        getContentPane().add(txtTerminalTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 288, 284, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 383, -1, -1));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 384, 305, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 383, -1, -1));

        btnPenumpang.setBackground(new java.awt.Color(5, 157, 192));
        btnPenumpang.setForeground(new java.awt.Color(255, 255, 255));
        btnPenumpang.setText("Penumpang");
        btnPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenumpangActionPerformed(evt);
            }
        });
        getContentPane().add(btnPenumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 124, -1, -1));

        btnTiket.setBackground(new java.awt.Color(5, 157, 192));
        btnTiket.setForeground(new java.awt.Color(255, 255, 255));
        btnTiket.setText("Tiket");
        btnTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiketActionPerformed(evt);
            }
        });
        getContentPane().add(btnTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 165, 89, -1));

        btnReservasi.setBackground(new java.awt.Color(5, 157, 192));
        btnReservasi.setForeground(new java.awt.Color(255, 255, 255));
        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 206, 89, -1));

        btnTransaksi.setBackground(new java.awt.Color(5, 157, 192));
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 247, 89, -1));

        btnKereta.setBackground(new java.awt.Color(5, 157, 192));
        btnKereta.setForeground(new java.awt.Color(255, 255, 255));
        btnKereta.setText("Bus");
        btnKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeretaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 83, 89, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("DATA BUS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DASHBOARD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 33, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 298, 89, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblBus.getModel();
        int row = tblBus.getSelectedRow();
        Bus bus = new Bus();
        
        bus = bus.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        
        txtIdBus.setText(String.valueOf(bus.getIdbus()));
        txtNamaBus.setText(bus.getNamabus());
        txtJamBerangkat.setText(bus.getJamberangkat());
        txtHargaTiket.setText(String.valueOf((bus.getHargatiket())));
        txtTerminalAsal.setText(bus.getTerminalasal());
        txtTerminalTujuan.setText(bus.getTerminaltujuan());
    }//GEN-LAST:event_tblBusMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Bus bus = new Bus();
        bus.setIdbus(Integer.parseInt(txtIdBus.getText()));
        bus.setNamabus(txtNamaBus.getText());
        bus.setJamberangkat(txtJamBerangkat.getText());
        bus.setHargatiket(Integer.parseInt(txtHargaTiket.getText()));
        bus.setTerminalasal(txtTerminalAsal.getText());
        bus.setTerminaltujuan(txtTerminalTujuan.getText());
        bus.save();
        
        txtIdBus.setText(Integer.toString(bus.getIdbus()));
        
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblBus.getModel();
        int row = tblBus.getSelectedRow();
        
        Bus bus = new Bus().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        bus.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenumpangActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPenumpang().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnPenumpangActionPerformed

    private void btnKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeretaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBus().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnKeretaActionPerformed

    private void btnTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiketActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTiket().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnTiketActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReservasi().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void kosongkanForm() {
        txtIdBus.setText("0");
        txtNamaBus.setText("");
        txtJamBerangkat.setText("");
        txtHargaTiket.setText("");
        txtTerminalAsal.setText("");
        txtTerminalTujuan.setText("");
    }
    
    public void tampilkanData() {
        String[] kolom = {"ID Bus", "Nama Bus", "Jam Berangkat", "Harga Tiket", "Terminal Asal", "Terminal Tujuan"};
        ArrayList<Bus> list = new Bus().getAll();
        Object rowData[] = new Object[7];
        
        tblBus.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Bus k : list) {
            rowData[0] = k.getIdbus();
            rowData[1] = k.getNamabus();
            rowData[2] = k.getJamberangkat();
            rowData[3] = k.getHargatiket();
            rowData[4] = k.getTerminalasal();
            rowData[5] = k.getTerminaltujuan();
            
            ((DefaultTableModel)tblBus.getModel()).addRow(rowData);
        }
    }
    
    public void cari(String keyword) {
        String[] kolom = {"ID Bus", "Nama Bus", "Jam Berangkat", "Harga Tiket", "Terminal Asal", "Terminal Tujuan"};
        ArrayList<Bus> list = new Bus().search(keyword);
        Object rowData[] = new Object[7];
        
        tblBus.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Bus k : list) {
            rowData[0] = k.getIdbus();
            rowData[1] = k.getNamabus();
            rowData[2] = k.getJamberangkat();
            rowData[3] = k.getHargatiket();
            rowData[4] = k.getTerminalasal();
            rowData[5] = k.getTerminaltujuan();
            
            ((DefaultTableModel)tblBus.getModel()).addRow(rowData);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKereta;
    private javax.swing.JButton btnPenumpang;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JButton btnTiket;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBus;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaTiket;
    private javax.swing.JTextField txtIdBus;
    private javax.swing.JTextField txtJamBerangkat;
    private javax.swing.JTextField txtNamaBus;
    private javax.swing.JTextField txtTerminalAsal;
    private javax.swing.JTextField txtTerminalTujuan;
    // End of variables declaration//GEN-END:variables
}
