package frontend;

import backend.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class FrmTiket extends javax.swing.JFrame {

    
    public FrmTiket() {
        initComponents();
        tampilkanData();
        tampilkanCmbKategori();
        kosongkanForm();
    }
    
    public void kosongkanForm() {
        txtIdTiket.setText("0");
        cmbBus.setSelectedIndex(0);
        txtJadwal.setText("");
        txtNoKursi.setText("");
        txtKelas.setText("");
    }
    
    public void tampilkanData() {
        String[] kolom = {"ID Tiket", "Bus", "Jadwal", "Nomor Kursi", "Kelas"};
        ArrayList<Tiket> list = new Tiket().getAll();
        Object rowData[] = new Object[5];
        
        tblTiket.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdtiket();
            rowData[1] = list.get(i).getBus().getNamabus();
            rowData[2] = list.get(i).getJadwal();
            rowData[3] = list.get(i).getNokursi();
            rowData[4] = list.get(i).getKelas();
            
            ((DefaultTableModel)tblTiket.getModel()).addRow(rowData);
        }
    }
    
    public void cari(String keyword) {
        String[] kolom = {"ID Tiket", "Bus", "Jadwal", "Nomor Kursi", "Kelas"};
        ArrayList<Tiket> list = new Tiket().search(keyword);
        Object rowData[] = new Object[5];
        
        tblTiket.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdtiket();
            rowData[1] = list.get(i).getBus().getNamabus();
            rowData[2] = list.get(i).getJadwal();
            rowData[3] = list.get(i).getNokursi();
            rowData[4] = list.get(i).getKelas();
            
            ((DefaultTableModel)tblTiket.getModel()).addRow(rowData);
        }
    }
    
    public void tampilkanCmbKategori() {
        cmbBus.setModel(new DefaultComboBoxModel(new Bus().getAll().toArray()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtIdTiket = new javax.swing.JTextField();
        txtJadwal = new javax.swing.JTextField();
        cmbBus = new javax.swing.JComboBox<>();
        txtNoKursi = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnKereta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnPenumpang = new javax.swing.JButton();
        btnTiket = new javax.swing.JButton();
        btnReservasi = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTiket.setBackground(new java.awt.Color(5, 157, 192));
        tblTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTiket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 342, 491, 103));

        jLabel1.setText("ID Tiket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 80, -1, -1));

        jLabel2.setText("Bus");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 118, -1, -1));

        jLabel3.setText("Jadwal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 156, -1, -1));

        jLabel4.setText("Nomor Kursi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 194, -1, -1));

        jLabel5.setText("Kelas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 232, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 267, -1, -1));

        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 301, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 301, -1, -1));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 302, 244, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 301, -1, -1));

        txtIdTiket.setEnabled(false);
        getContentPane().add(txtIdTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 77, 76, -1));

        txtJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJadwalActionPerformed(evt);
            }
        });
        getContentPane().add(txtJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 153, 204, -1));

        cmbBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 115, 204, -1));
        getContentPane().add(txtNoKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 191, 204, -1));

        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        getContentPane().add(txtKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 229, 204, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DATA TIKET");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 27, -1, -1));

        btnKereta.setBackground(new java.awt.Color(5, 157, 192));
        btnKereta.setForeground(new java.awt.Color(255, 255, 255));
        btnKereta.setText("Bus");
        btnKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeretaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 77, 89, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("DASHBOARD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 27, -1, -1));

        btnPenumpang.setBackground(new java.awt.Color(5, 157, 192));
        btnPenumpang.setForeground(new java.awt.Color(255, 255, 255));
        btnPenumpang.setText("Penumpang");
        btnPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenumpangActionPerformed(evt);
            }
        });
        getContentPane().add(btnPenumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 118, -1, -1));

        btnTiket.setBackground(new java.awt.Color(5, 157, 192));
        btnTiket.setForeground(new java.awt.Color(255, 255, 255));
        btnTiket.setText("Tiket");
        btnTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiketActionPerformed(evt);
            }
        });
        getContentPane().add(btnTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, 89, -1));

        btnReservasi.setBackground(new java.awt.Color(5, 157, 192));
        btnReservasi.setForeground(new java.awt.Color(255, 255, 255));
        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 200, 89, -1));

        btnTransaksi.setBackground(new java.awt.Color(5, 157, 192));
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 241, 89, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 301, 89, -1));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJadwalActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKelasActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Tiket tiket = new Tiket();
        tiket.setIdtiket(Integer.parseInt(txtIdTiket.getText()));
        tiket.setBus((Bus)cmbBus.getSelectedItem());
        tiket.setJadwal(txtJadwal.getText());
        tiket.setNokursi(txtNoKursi.getText());
        tiket.setKelas(txtKelas.getText());
        tiket.save();
        
        txtIdTiket.setText(Integer.toString(tiket.getIdtiket()));
        
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTiket.getModel();
        int row = tblTiket.getSelectedRow();
        
        Tiket tiket = new Tiket().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        tiket.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiketMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTiket.getModel();
        int row = tblTiket.getSelectedRow();
        
        Tiket tiket = new Tiket();
        
        tiket = tiket.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        
        txtIdTiket.setText(String.valueOf(tiket.getIdtiket()));
        cmbBus.getModel().setSelectedItem(tiket.getBus().getNamabus());
        txtJadwal.setText(tiket.getJadwal());
        txtNoKursi.setText(tiket.getNokursi());
        txtKelas.setText(tiket.getKelas());
    }//GEN-LAST:event_tblTiketMouseClicked

    private void btnKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeretaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBus().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnKeretaActionPerformed

    private void btnPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenumpangActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPenumpang().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnPenumpangActionPerformed

    private void btnTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiketActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTiket().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnTiketActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReservasi().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKereta;
    private javax.swing.JButton btnPenumpang;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JButton btnTiket;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox<String> cmbBus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTiket;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdTiket;
    private javax.swing.JTextField txtJadwal;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNoKursi;
    // End of variables declaration//GEN-END:variables
}
